### ISSUE TITLE
List of incompatibilities between cmetrics and prometheus

### ISSUE THREAD

**Issue by tarruda** [calyptia/cmetrics#70]
I'm listing some issues that might need to be fixed in cmetrics API to make it compatible with prometheus metrics:

- [x] Special characters such as \ , " and \n inside label values and HELP docstrings are not escaped by the prometheus encoder (fixed by #80)
- [x] Help/docstring is optional in prometheus text format, but required by the API (fixed by #81)
- [x] Label ordering assumed by cmetrics are not necessarily true. I've tested a few examples that had different labels on the same metric and it was accepted by `promtool`, but it is not currently possible to express in cmetrics (fixed by #94 and #99)
